### ISSUE TITLE
Dates should have some sort of limitation OR the activity feed should be filtered some other way

### ISSUE THREAD

**Issue by zapbampow** [SingleSpeed/Brewgr.com#6]
A user can put in any date up to 12/31/9999 for brew sessions or tasting notes. Because the home page activity feed is just the tasting notes ordered in descending order, if someone gives a high date, it just sits at the top of the activity feed forever. 

In other words, it doesn't actually show the latest activity. If dates were limited so some max date (today, a week from today, a month from today) then the activity feed would again have some meaning. OR if the feed were sorted by updated date then it would also have some meaning.

**Comment by thirossato** [comment]
Good point, I think it make sense to sort by updated date

**Comment by SingleSpeed** [comment]
I have updated the bad data. I will fix this soon.
